name: Build & Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build Java JAR
      - name: Build Java App
        run: |
          cd application-service
          mvn clean package

      # Build Docker image (Java)
      - name: Build Java Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/hackathon-repo/app-service:latest ./application-service

      # Build Docker image (Node)
      - name: Build Node Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/hackathon-repo/order-service:latest ./order-service

      # Push Images
      - name: Push Images
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/hackathon-repo/app-service:latest
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/hackathon-repo/order-service:latest
          
