name: Build & Push to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: hcl-devops-hackathon
  REGION: asia-south1
  REPO: my-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      # Node builds
      - name: Build application-service
        run: |
          docker build -t ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/application-service:latest ./application-service

      - name: Build patient-service
        run: |
          docker build -t ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/patient-service:latest ./patient-service

      # Java build
      - name: Build order-service
        run: |
          cd order-service
          mvn clean package -DskipTests
          cd ..
          docker build -t ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/order-service:latest ./order-service

      # Push images
      - name: Push images
        run: |
          docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/application-service:latest
          docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/patient-service:latest
          docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/$REPO/order-service:latest
          
