name: GCP Auth Test

on:
  push:
    branches: [ "main" ]

jobs:
  auth-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # ðŸ”¥ REQUIRED for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/943434175374/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-deployer@hcl-devops-hackathon-486008.iam.gserviceaccount.com"

      - name: Verify Auth
        run: gcloud auth list
